### PR TITLE
Make rules available as a plugin fixes #4

### LINKED ISSUE #4: Package up as eslint-plugin for easier deployment
Hi Gleb.

Can this get packaged up in the eslint-plugin-* format so it can be installed and automated via regular tooling?

### PR DESCRIPTION
**Pull request by ericwooley**
Fixes #4

### CODE REVIEW

**Comment by ericwooley** [comment]
I'm having a hard time figuring out your unit tests, it says `Error: Cannot find module 'collections/shim'`, not sure what the deal is, but I only added an index file and change the package.json info.

**Comment by bahmutov** [comment]
published as 0.6.0

**Comment by ericwooley** [comment]
Awesome, thanks!

**Comment by mattdell** [comment]
This thread was a very useful guide for how to use this in my project. Could we update the readme to include the steps...

* Add `'extra-rules'` to plugins in .eslintrc
* Prefix rules with extra-rules (i.e. - `extra-rules/no-commented-out-code: 2`)

@bahmutov ?

**Comment by bahmutov** [comment]
@mattdell sure, but maybe you could make the changes and add a pull request? I promise to merge it ASAP

**Pull request merged**
